INSERT INTO car (id,class,name,year) VALUES (0, 'GT3', 'Porsche 991 GT3 R',2018) ON CONFLICT (id) DO NOTHING;
INSERT INTO car (id,class,name,year) VALUES (1, 'GT3', 'Mercedes-AMG GT3',2015) ON CONFLICT (id) DO NOTHING;
INSERT INTO car (id,class,name,year) VALUES (2, 'GT3', 'Ferrari 488 GT3',2018) ON CONFLICT (id) DO NOTHING;
INSERT INTO car (id,class,name,year) VALUES (3, 'GT3', 'Audi R8 LMS',2015) ON CONFLICT (id) DO NOTHING;
INSERT INTO car (id,class,name,year) VALUES (4, 'GT3', 'Lamborghini Huracan GT3',2015) ON CONFLICT (id) DO NOTHING;
INSERT INTO car (id,class,name,year) VALUES (5, 'GT3', 'McLaren 650S GT3',2015) ON CONFLICT (id) DO NOTHING;
INSERT INTO car (id,class,name,year) VALUES (6, 'GT3', 'Nissan GT-R Nismo GT3',2018) ON CONFLICT (id) DO NOTHING;
INSERT INTO car (id,class,name,year) VALUES (7, 'GT3', 'BMW M6 GT3',2017) ON CONFLICT (id) DO NOTHING;
INSERT INTO car (id,class,name,year) VALUES (8, 'GT3', 'Bentley Continental GT3',2018) ON CONFLICT (id) DO NOTHING;
INSERT INTO car (id,class,name,year) VALUES (9, 'CUP', 'Porsche 991 II GT3 Cup',2017) ON CONFLICT (id) DO NOTHING;
INSERT INTO car (id,class,name,year) VALUES (10,'GT3', 'Nissan GT-R Nismo GT3',2015) ON CONFLICT (id) DO NOTHING;
INSERT INTO car (id,class,name,year) VALUES (11,'GT3', 'Bentley Continental GT3',2015) ON CONFLICT (id) DO NOTHING;
INSERT INTO car (id,class,name,year) VALUES (12,'GT3', 'AMR V12 Vantage GT3',2013) ON CONFLICT (id) DO NOTHING;
INSERT INTO car (id,class,name,year) VALUES (13,'GT3', 'Reiter Engineering R-EX GT3',2017) ON CONFLICT (id) DO NOTHING;
INSERT INTO car (id,class,name,year) VALUES (14,'GT3', 'Emil Frey Jaguar G3',2012) ON CONFLICT (id) DO NOTHING;
INSERT INTO car (id,class,name,year) VALUES (15,'GT3', 'Lexus RC F GT3',2016) ON CONFLICT (id) DO NOTHING;
INSERT INTO car (id,class,name,year) VALUES (16,'GT3', 'Lamborghini Huracan GT3 Evo',2019) ON CONFLICT (id) DO NOTHING;
INSERT INTO car (id,class,name,year) VALUES (17,'GT3', 'Honda NSX GT3',2017) ON CONFLICT (id) DO NOTHING;
INSERT INTO car (id,class,name,year) VALUES (18,'ST', 'Lamborghini Huracan SuperTrofeo',2015) ON CONFLICT (id) DO NOTHING;
INSERT INTO car (id,class,name,year) VALUES (19,'GT3', 'Audi R8 LMS Evo',2019) ON CONFLICT (id) DO NOTHING;
INSERT INTO car (id,class,name,year) VALUES (20,'GT3', 'AMR V8 Vantage',2019) ON CONFLICT (id) DO NOTHING;
INSERT INTO car (id,class,name,year) VALUES (21,'GT3', 'Honda NSX GT3 Evo',2019) ON CONFLICT (id) DO NOTHING;
INSERT INTO car (id,class,name,year) VALUES (22,'GT3', 'McLaren 720S GT3',2019) ON CONFLICT (id) DO NOTHING;
INSERT INTO car (id,class,name,year) VALUES (23,'GT3', 'Porsche 911 II GT3 R',2019) ON CONFLICT (id) DO NOTHING;
INSERT INTO car (id,class,name,year) VALUES (24,'GT3', 'Ferrari 488 GT3 Evo',2020) ON CONFLICT (id) DO NOTHING;
INSERT INTO car (id,class,name,year) VALUES (25,'GT3', 'Mercedes-AMG GT3',2020) ON CONFLICT (id) DO NOTHING;
INSERT INTO car (id,class,name,year) VALUES (26,'CHL', 'Ferrari 488 Challenge Evo',2020) ON CONFLICT (id) DO NOTHING;
INSERT INTO car (id,class,name,year) VALUES (27,'TCX', 'BMW M2 CS Racing',2020) ON CONFLICT (id) DO NOTHING;
INSERT INTO car (id,class,name,year) VALUES (28,'CUP', 'Porsche 911 GT3 Cup (Type 992)',2021) ON CONFLICT (id) DO NOTHING;
INSERT INTO car (id,class,name,year) VALUES (29,'ST', 'Lamborghini Huracan Super Trofeo EVO2',2021) ON CONFLICT (id) DO NOTHING;
INSERT INTO car (id,class,name,year) VALUES (30,'GT3', 'BMW M4 GT3',2022) ON CONFLICT (id) DO NOTHING;
INSERT INTO car (id,class,name,year) VALUES (31,'GT3', 'Audi R8 LMS GT3 evo II',2022) ON CONFLICT (id) DO NOTHING;
INSERT INTO car (id,class,name,year) VALUES (50,'GT4', 'Alpine A110 GT4',2018) ON CONFLICT (id) DO NOTHING;
INSERT INTO car (id,class,name,year) VALUES (51,'GT4', 'Aston Martin Vantage GT4',2018) ON CONFLICT (id) DO NOTHING;
INSERT INTO car (id,class,name,year) VALUES (52,'GT4', 'Audi R8 LMS GT4',2018) ON CONFLICT (id) DO NOTHING;
INSERT INTO car (id,class,name,year) VALUES (53,'GT4', 'BMW M4 GT4',2018) ON CONFLICT (id) DO NOTHING;
INSERT INTO car (id,class,name,year) VALUES (54,'C54', 'Car 54 Where are you?',1961) ON CONFLICT (id) DO NOTHING;
INSERT INTO car (id,class,name,year) VALUES (55,'GT4', 'Chevrolet Camaro GT4',2017) ON CONFLICT (id) DO NOTHING;
INSERT INTO car (id,class,name,year) VALUES (56,'GT4', 'Ginetta G55 GT4',2012) ON CONFLICT (id) DO NOTHING;
INSERT INTO car (id,class,name,year) VALUES (57,'GT4', 'KTM X-Bow GT4',2016) ON CONFLICT (id) DO NOTHING;
INSERT INTO car (id,class,name,year) VALUES (58,'GT4', 'Maserati MC GT4',2016) ON CONFLICT (id) DO NOTHING;
INSERT INTO car (id,class,name,year) VALUES (59,'GT4', 'McLaren 570S GT4',2016) ON CONFLICT (id) DO NOTHING;
INSERT INTO car (id,class,name,year) VALUES (60,'GT4', 'Mercedes AMG GT4',2016) ON CONFLICT (id) DO NOTHING;
INSERT INTO car (id,class,name,year) VALUES (61,'GT4', 'Porsche 718 Cayman GT4 Clubsport',2019) ON CONFLICT (id) DO NOTHING;