name: Parse Files

on:
  schedule:
    - cron: "*/15 * * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Call file parser lambda
      uses: fjogeleit/http-request-action@master
      with:
        url:  ${{ secrets.PULLER_URL }}
        method: 'GET'
        timeout: 30000
        preventFailureOnNoResponse: true
        ignoreStatusCodes: '500'
