name: Kickoff Poller

on:
  schedule:
    - cron: "*/60 * * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Dump secret
      run: echo "${{ secrets.POLLER_URL }}"
    - name: Call poller lambda
      uses: fjogeleit/http-request-action@master
      with:
        url:  ${{ secrets.POLLER_URL }}
        method: 'GET'
        timeout: 30000
        preventFailureOnNoResponse: true
