name: Kickoff Poller

on:
  push:
    branches:
      - master
  schedule:
    - cron: "*/15 * * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Dump secret
      env:
        POLLER_URL: ${{ secrets.POLLER_URL }}
      run: echo "$POLLER_URL"
    - name: Call poller lambda
      env:
        POLLER_URL: ${{ secrets.POLLER_URL }}
      uses: fjogeleit/http-request-action@master
      with:
        url: ${{ POLLER_URL }}
        method: 'GET'
        timeout: 30000
        preventFailureOnNoResponse: true
