name: Update Elo

on:
  schedule:
    - cron: "*/5 * * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Call elo update lambda
      uses: fjogeleit/http-request-action@master
      with:
        url:  '${{ secrets.API_ROOT }}/updateElo'
        method: 'GET'
        timeout: 30000
        preventFailureOnNoResponse: true
        ignoreStatusCodes: '500'
